DEBUG=1
# RELEASE=1
# FACTORY=1
TEST_USE_WEB_SOCKET = 1
# BUILD_LINUX64=1
BUILD_ARM_VVTK=1

# FEATURE_RTMP=1
# FEATURE_AI=1
# VOICE_GUIDE=1
# FEATURE_RECORD=1

#######################################################
# build agent
#######################################################

# BUILD_PLAY3=1
BUILD_IQ3=1
# BUILD_SE2=1

PROJECT_AGENT=agent
BUILD_DIR=../firmware
RELEASE_DIR=../release
HAL_OTA_DIR=../240322

VERSION=1.0.6
VENDOR='FPTCamera'

PRODUCT_PLAY3=P03S
PRODUCT_IQ3=I03S
PRODUCT_SE2=S02L

HARDWARE_PLAY3=2220-$(PRODUCT_PLAY3)-R18N
HARDWARE_IQ3=2220-$(PRODUCT_IQ3)-R18N
HARDWARE_SE2=2220-$(PRODUCT_SE2)-R17N

MODEL_PLAY3='FPT Camera Play 3'
MODEL_IQ3='FPT Camera IQ 3S'
MODEL_SE2='FPT Camera SE 2'

MONTH_CURR=`date +'20%y.%m'`
DATE_CURR=`date +'20%y.%m.%d'`
BUILD_TIME=`date +'%H.%M.%S'`
NAME_SDK=$(NAME_MODULE)_$(VERSION)_$(DATE_CURR)

BUILD_ERROR = ''

ifdef BUILD_PLAY3
FW_NAME=$(VERSION)-$(HARDWARE_PLAY3)-$(DATE_CURR)T$(BUILD_TIME)
FW_MODEL=$(MODEL_PLAY3)
FW_PRODUCT=$(PRODUCT_PLAY3)
GENERAL_FLAGS += -DBUILD_PLAY3
RELEASE_MODEL=P03S-R18N
FW_RELEASE=$(VERSION)-$(HARDWARE_PLAY3)-*.bin
else
ifdef BUILD_IQ3
FW_NAME=$(VERSION)-$(HARDWARE_IQ3)-$(DATE_CURR)T$(BUILD_TIME)
FW_MODEL=$(MODEL_IQ3)
FW_PRODUCT=$(PRODUCT_IQ3)
GENERAL_FLAGS += -DBUILD_IQ3
RELEASE_MODEL=I03S-R18N
FW_RELEASE=$(VERSION)-$(HARDWARE_IQ3)-*.bin
else
ifdef BUILD_SE2
FW_NAME=$(VERSION)-$(HARDWARE_SE2)-$(DATE_CURR)T$(BUILD_TIME)
FW_MODEL=$(MODEL_SE2)
FW_PRODUCT=$(PRODUCT_SE2)
GENERAL_FLAGS += -DBUILD_SE2
else
BUILD_ERROR='Model not support'
endif
endif
endif


 
